# This is an example mods.toml file. It contains the data relating to the loading mods.
modLoader="javafml" #mandatory
license="MIT"

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[6,)" #mandatory

# A URL to refer people to when problems occur with this mod
issueTrackerURL=""

[[mods]] #mandatory
modId="nopoof" #mandatory
version="1.0.0" #mandatory
displayName="No Poof" #mandatory
updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/_curseslug_"
logoFile=""
credits=""
authors="Raiiiden"
description='''Removes the death particle'''

[[dependencies.nopoof]] #mandatory
modId="forge"
mandatory=true
versionRange="[47.3,)"
ordering="NONE"
side="BOTH"

[[dependencies.nopoof]]
modId="minecraft"
mandatory=true
versionRange="[1.20,)"
ordering="NONE"
side="BOTH"
